version: '2.2'
services:
  otus-sales-leads-generator-app-api-test:
    container_name: otus-sales-leads-generator-app-api-test
    image: $nexus_image
    environment:
      MODE: test
      DB: 'otusDB'
    mem_limit: '1024288000'
    oom_kill_disable: false
    mem_swappiness: 10
    memswap_limit: 10737418240
    cpus: 1
    restart: always
    volumes:
    - otus-sales-leads-generator-app_logs:/var/logs
    entrypoint: /bin/sh /run_jar.sh
    tty: true
    dns_opt:
      - ndots:1
volumes:
  otus-sales-leads-generator-app_logs: {}

