version: '2.4'
services:
  otus-sales-leads-generator-app-bot-dev:
    container_name: otus-sales-leads-generator-app-bot-dev
    image: otus/otus-sales-leads-generator-app-bot
    build:
      context: ../
      dockerfile: apps/bot/Dockerfile
    environment:
      MODE: dev
      TOKEN: '1967675782:AAHX6RgBeQktXWB3J9okfi2cBe28BhAwwPI'
      API_HOST: 'otus-sales-leads-generator-app-api-dev'
      API_PORT: 4080
    volumes:
    - otus-sales-leads-generator-bot_logs:/var/logs
    entrypoint: /bin/sh /run_jar.sh
    tty: true
    dns_opt:
      - ndots:1
volumes:
  otus-sales-leads-generator-bot_logs: {}
