version: '3'
services:

  #db:
  #  image: postgres
  #  restart: on-failure
  #  hostname: postgre-sql
  #  container_name: postgre-sql
  #  ports:
  #  - "5432:5432"
  #  expose:
  #  - "5432"
  #  environment:
  #    POSTGRES_USER: crm_dev
  #    POSTGRES_PASSWORD: crm123

  otusDB:
    image: postgres:latest
    container_name: otusDB
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=otus"
      - "POSTGRES_PASSWORD=otus"
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"      
      
  adminer:
    image: adminer
    restart: on-failure
    ports:
    - 8080:8080
